steps:

  - name: gcr.io/cloud-builders/npm
    args: [ install ]

  - name: gcr.io/cloud-builders/npm
    args: [ run, build, --prod ]

  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "build",
        "-t",
        "gcr.io/avatar-419000/github.com/fjborquez/katara:$SHORT_SHA",
        "-t",
        "gcr.io/avatar-419000/github.com/fjborquez/katara:latest",
        ".",
      ]
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "push",
        "gcr.io/avatar-419000/github.com/fjborquez/katara:$SHORT_SHA",
      ]
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "push",
        "gcr.io/avatar-419000/github.com/fjborquez/katara:latest",
      ]
  - name: "gcr.io/cloud-builders/gcloud"
    args:
      [
        "run",
        "deploy",
        "katara",
        "--image",
        "gcr.io/avatar-419000/github.com/fjborquez/katara:$SHORT_SHA",
        "--region",
        "southamerica-east1",
        "--platform",
        "managed",
        "--verbosity",
        "debug",
        "--memory",
        "128Mi",
        "--cpu",
        "2000m",
        "--port",
        "80",
        "--timeout",
        "3600",
        "--min-instances",
        "0",
      ]
    env:
      - "PORT=80"
images:
  - gcr.io/avatar-419000/github.com/fjborquez/katara:$SHORT_SHA
  - gcr.io/avatar-419000/github.com/fjborquez/katara:latest
timeout: 2400s
